

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AbejaCruz (https://sketchfab.com/AbejaCruz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/arlo-the-good-dinosaur-b86ea7d0655f462fa78a973c23401646
Title: Arlo - The Good Dinosaur
*/

import React from 'react' 
import { useGLTF } from '@react-three/drei'
const Dino = (props) => {
  const { nodes, materials } = useGLTF('../dino.glb') 
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[6.092, 0.145, 7.535]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_0.geometry}
            material={materials.Material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_1.geometry}
            material={materials['Material.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_2.geometry}
            material={materials['Material.005']}
          />
        </group>
        <group position={[6.148, -0.332, 8.181]} rotation={[0.991, 0.804, 0.503]} scale={0.347}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere_0.geometry}
            material={materials['Material.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere_1.geometry}
            material={materials['Material.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere_2.geometry}
            material={materials['Material.003']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_0.geometry}
          material={materials['Material.001']}
          position={[7.639, -0.354, 6.229]}
          rotation={[-3.122, -0.123, -0.162]}
          scale={[0.251, 0.113, 0.146]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_0.geometry}
          material={materials['Material.004']}
          position={[6.523, -0.017, 6.333]}
          scale={[1, 0.336, 1]}
        />
      </group>
    </group>
  )
}

export default Dino; 
